import { useState } from 'react'
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, FileCheck2, Film, FolderOpen, Globe2, Image, Layers3, Music2, Play, Plus, Search, ShieldCheck, Sparkles, X, AlertCircle } from 'lucide-react'
import { toast } from 'sonner'
import type { StudioSummary, DecisionRecord, ProvenanceGraphData, PreflightVerdict } from '@/types'
import type { TabType } from '@/components/layout/Sidebar'
import { api, assetName, readableJson, reasonLabel } from '@/lib/api'
import { Button } from '@/components/ui/Button'
import { Badge } from '@/components/ui/Badge'
import { Modal } from '@/components/ui/Modal'
interface Props { summary: StudioSummary | null; decisions: DecisionRecord[]; graph: ProvenanceGraphData | null; onRefresh: () => void; onNavigateTab: (tab: TabType) => void; examplesOnly?: boolean }
const examples = [
  { asset: 'ast_talent_frame_v1', channel: 'social', title: 'A social-ready portrait', text: 'Check a character portrait for a social media release.', label: 'Social media', expected: 'Explore likeness consent', icon: Image, tone: 'lavender' },
  { asset: 'ast_composite_v1', channel: 'festival', title: 'From edit to festival', text: 'See how a film and its music are checked together.', label: 'Film festival', expected: 'Explore combined rights', icon: Film, tone: 'peach' },
  { asset: 'ast_music_bed_v1', channel: 'trailer', title: 'The right track. The wrong rights?', text: 'Find out why festival music may not cover a trailer.', label: 'Trailer release', expected: 'Explore a blocked check', icon: Music2, tone: 'mint' },
]
export function OverviewPage({ summary, decisions, graph, onRefresh, onNavigateTab, examplesOnly = false }: Props) {
  const [checkingOpen, setCheckingOpen] = useState(false)
  const [asset, setAsset] = useState('')
  const [channel, setChannel] = useState('social')
  const [territory, setTerritory] = useState('US')
  const [checking, setChecking] = useState(false)
  const [verdict, setVerdict] = useState<PreflightVerdict | null>(null)
  const [checkError, setCheckError] = useState('')
  const [filter, setFilter] = useState('all')
  const [search, setSearch] = useState('')
  const [trace, setTrace] = useState<DecisionRecord | null>(null)
  const [video, setVideo] = useState(false)
  const [allActivity, setAllActivity] = useState(false)
  const nodes = graph?.nodes || []
  const selectedAsset = asset || nodes[0]?.id || ''
  const openCheck = (example?: typeof examples[number]) => {
    setAsset(example?.asset || nodes[0]?.id || ''); setChannel(example?.channel || 'social'); setTerritory('US'); setVerdict(null); setCheckError(''); setCheckingOpen(true)
  }
  const runCheck = async () => {
    setChecking(true); setCheckError(''); setVerdict(null)
    try { const result = await api.runPreflight({ asset_id: selectedAsset, channel, territory }); setVerdict(result); onRefresh() }
    catch { setCheckError('We couldn’t complete this check. Please try again. No clearance has been confirmed.') }
    finally { setChecking(false) }
  }
  const filtered = decisions.filter(d => (filter === 'all' || (filter === 'allowed' ? d.allowed : !d.allowed)) && `${assetName(d.asset_id)} ${d.asset_id} ${d.channel || ''}`.toLowerCase().includes(search.toLowerCase())).slice().reverse()
  const stats = [
    { label: 'Assets in your workspace', value: summary?.studio_assets ?? '—', detail: 'Ready to explore', icon: FolderOpen, tone: 'mint', action: 'provenance' },
    { label: 'Clearance pass rate', value: decisions.length ? `${Math.round((summary?.clearance_rate || 0) * 100)}%` : '—', detail: decisions.length ? `${summary?.allows || 0} of ${decisions.length} checks cleared` : 'Run your first check', icon: ShieldCheck, tone: 'mint', action: 'analytics' },
    { label: 'Awaiting approval', value: summary?.pending_approvals ?? '—', detail: summary?.pending_approvals ? 'Needs your attention' : 'You’re all caught up', icon: Clock3, tone: 'peach', action: 'countersign' },
    { label: 'Verified rights records', value: summary?.verified_claims ?? '—', detail: 'Signed content credentials', icon: FileCheck2, tone: 'lavender', action: 'provenance' },
  ]
  const gallery = <section className="examples-section"><div className="section-heading"><div><h2>{examplesOnly ? 'Choose a starting point' : 'A little inspiration to get started'}</h2><p>Real scenarios. Sample assets. No upload needed.</p></div>{!examplesOnly && <button className="text-link" onClick={() => onNavigateTab('examples')}>Explore examples <ArrowRight size={15} /></button>}</div><div className="example-grid">{examples.map((ex, i) => <button className={`example-card ${ex.tone}`} key={ex.asset} onClick={() => openCheck(ex)} disabled={!nodes.some(n => n.id === ex.asset)}><div className="example-top"><span className={`example-icon ${ex.tone}`}><ex.icon size={22} /></span><span className="example-category">{ex.label}</span><ArrowUpRight size={17} /></div><h3>{ex.title}</h3><p>{ex.text}</p><div className="example-bottom"><span>{ex.expected}</span><span className="example-number">0{i + 1}</span></div></button>)}</div></section>
  return <div className="page-stack">
    <div className="page-heading"><div><div className="heading-kicker">YOUR CLEARANCE WORKSPACE <span className="sample-pill">Sample data</span></div><h1>{examplesOnly ? 'Explore what’s possible.' : 'A clear view. A confident next step.'}</h1><p>{examplesOnly ? 'Try a guided scenario and see your rights checks in action.' : 'Your assets, permissions, and peace of mind. All in one place.'}</p></div><div className="heading-actions"><Button variant="secondary" onClick={() => onNavigateTab('certificates')}><ArrowDownToLine size={16} />Export report</Button><Button onClick={() => openCheck()}><Plus size={17} />New clearance check</Button></div></div>
    {!examplesOnly && <>
      <div className="stats-grid">{stats.map(stat => <button className="stat-card" key={stat.label} onClick={() => onNavigateTab(stat.action as TabType)}><div className="stat-top"><span>{stat.label}</span><span className={`stat-icon ${stat.tone}`}><stat.icon size={18} /></span></div><div className="stat-value">{stat.value}<svg className={`mini-spark ${stat.tone}`} viewBox="0 0 88 32" aria-hidden="true"><path d="M2 26 L14 24 L25 26 L36 16 L46 20 L57 12 L68 15 L85 3" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" /></svg></div><div className="stat-detail">{stat.label === 'Awaiting approval' && !summary?.pending_approvals ? <CheckCircle2 size={13} /> : <span className={`tiny-dot ${stat.tone}`} />}{stat.detail}<ChevronRight size={14} /></div></button>)}</div>
      <section className="welcome-banner"><div className="welcome-copy"><span className="welcome-eyebrow"><Sparkles size={14} /> CREATE FREELY. PUBLISH CONFIDENTLY.</span><h2>Great work deserves<br />a clear path to the world.</h2><p>Know what you can use, where you can share it,<br className="desktop-br" /> and what needs a second look. Before you hit publish.</p><div className="welcome-actions"><Button onClick={() => openCheck()}>Check an asset <ArrowRight size={16} /></Button><button onClick={() => onNavigateTab('examples')} className="welcome-link"><Play size={13} />Try an example</button></div></div><div className="rights-illustration" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="illustration-line line-one" /><div className="illustration-line line-two" /><div className="source-chip source-video"><span><Film size={21} /></span><div><strong>Your video</strong><small>Content credentials</small></div><CheckCircle2 size={15} /></div><div className="source-chip source-audio"><span><Music2 size={21} /></span><div><strong>Your soundtrack</strong><small>Usage permissions</small></div><CheckCircle2 size={15} /></div><div className="clearance-orb"><ShieldCheck size={48} strokeWidth={1.3} /></div><div className="clearance-chip"><span className="check-disc"><Check size={13} /></span>Clarity for every creation</div><span className="illustration-spark spark-one">+</span><span className="illustration-spark spark-two">+</span></div></section>
      <div className="overview-columns"><section className="card activity-card"><div className="card-header"><div><h2>Recent clearance activity <span className="count-label">{decisions.length}</span></h2><p>A little more certainty with every check.</p></div><button className="text-link" onClick={() => setAllActivity(!allActivity)}>{allActivity ? 'Show recent' : 'View all'} <ArrowUpRight size={15} /></button></div><div className="activity-toolbar"><div className="segmented" aria-label="Filter clearance activity">{[['all','All checks'],['allowed','Cleared'],['denied','Needs attention']].map(([value,label]) => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)} className={filter === value ? 'selected' : ''}>{label}</button>)}</div><label className="search-box"><Search size={16} /><input aria-label="Search clearance activity" placeholder="Search assets…" value={search} onChange={e => setSearch(e.target.value)} /></label></div><div className="table-scroll"><table className="activity-table"><thead><tr><th>Asset</th><th>Destination</th><th>Status</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{filtered.slice(0, allActivity ? 100 : 4).map(d => <tr key={d.decision_id}><td><div className="asset-cell"><span className={`file-icon ${d.asset_id.includes('music') ? 'peach' : 'lavender'}`}>{d.asset_id.includes('music') ? <Music2 size={18} /> : <Film size={18} />}</span><div><strong>{assetName(d.asset_id)}</strong><small>{new Date(d.ts).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</small></div></div></td><td><span className="capitalize">{d.channel || d.verb}</span><small className="table-sub">{d.territory || 'Not specified'}</small></td><td><Badge variant={d.allowed ? 'success' : 'warning'}><span className="status-dot" />{d.allowed ? 'Cleared' : 'Needs attention'}</Badge></td><td><button className="icon-button" aria-label={`View decision ${d.decision_id}`} onClick={() => setTrace(d)}><ChevronRight size={17} /></button></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state"><ShieldCheck size={30} /><h3>{decisions.length ? 'No checks match your search' : 'Your next step starts here'}</h3><p>{decisions.length ? 'Try another asset name or choose a different status.' : 'Run a sample check to see a clear result and its supporting evidence.'}</p><Button variant="secondary" size="sm" onClick={() => decisions.length ? (setFilter('all'), setSearch('')) : openCheck()}>{decisions.length ? 'Clear filters' : 'Run your first check'}<ArrowRight size={14} /></Button></div>}</div><div className="activity-footer"><span><span className="tiny-dot mint" />{filtered.length ? `Showing ${Math.min(filtered.length, allActivity ? 100 : 4)} of ${filtered.length} checks` : 'Your checks will appear here'}</span><span>Updates automatically</span></div></section>
      <aside className="card project-card"><div className="card-header"><h2>In the spotlight</h2><span className="sample-pill">Sample project</span></div><button className="project-visual" onClick={() => setVideo(true)} aria-label="Play The Last Echo sample film"><img src="/media/ast_composite_v1.jpg" alt="Cinematic nighttime city scene from The Last Echo" /><span className="project-visual-shade" /><span className="project-film-tag"><Film size={12} />AI SHORT FILM</span><span className="play-circle"><Play size={21} fill="currentColor" /></span><span className="project-visual-caption">THE LAST ECHO<span>A study in light. A story in motion.</span></span></button><div className="project-body"><div><h3>The Last Echo</h3><span className="project-category">AI-assisted short film · Sample production</span></div><div className="project-facts"><span><Layers3 size={14} />{nodes.length} assets</span><span><Globe2 size={14} />Rights-aware production</span></div><button className="project-link" onClick={() => onNavigateTab('provenance')}>Explore project assets <ArrowRight size={16} /></button></div></aside></div>
    </>}
    {gallery}
    {examplesOnly && <div className="notice"><CircleHelp size={20} /><div><strong>Practice without publishing</strong><p>Each example fills in a clearance check for you. Review the asset and destination, then run it. Results reflect the current sample rights, which can change after an approval. Checks create audit records but never publish media.</p></div></div>}
    <Modal isOpen={checkingOpen} onClose={() => { if (!checking) setCheckingOpen(false) }} title="Can I publish this asset?">
      <p className="modal-intro">Tell us what you’d like to share. We’ll check the recorded permissions and explain your next step.</p><div className="inline-sample"><Sparkles size={15} /> Sample workspace · No media will be published</div>
      <form onSubmit={e => { e.preventDefault(); void runCheck() }}><fieldset disabled={checking} className="check-fields"><label htmlFor="check-asset">Which asset?<select id="check-asset" value={selectedAsset} onChange={e => { setAsset(e.target.value); setVerdict(null) }} required>{nodes.map(n => <option value={n.id} key={n.id}>{assetName(n.id)}</option>)}</select></label><div className="form-row"><label htmlFor="check-channel">Where will it be shared?<select id="check-channel" value={channel} onChange={e => { setChannel(e.target.value); setVerdict(null) }}><option value="social">Social media</option><option value="festival">Film festival</option><option value="trailer">Promotional trailer</option><option value="theatrical">Theatrical release</option></select></label><label htmlFor="check-territory">In which region?<select id="check-territory" value={territory} onChange={e => { setTerritory(e.target.value); setVerdict(null) }}><option value="US">United States</option><option value="EU">European Union</option><option value="Global">Worldwide</option></select></label></div><Button type="submit" isLoading={checking} disabled={!selectedAsset} className="full-width"><ShieldCheck size={17} />{checking ? 'Checking permissions…' : 'Check clearance'}</Button></fieldset></form>
      {checkError && <div className="result result-error" role="alert"><AlertCircle size={20} /><p>{checkError}</p></div>}
      {verdict && <div className={`result ${verdict.allowed ? 'result-success' : 'result-warning'}`} role="status">{verdict.allowed ? <ShieldCheck size={25} /> : <AlertCircle size={25} />}<div><h3>{verdict.allowed ? 'You’re cleared for this use' : 'This use needs a closer look'}</h3><p>{verdict.allowed ? `The recorded permissions cover ${channel} distribution in ${territory}. This result applies only to the use you checked.` : `${reasonLabel(verdict.reason)}. The recorded rights don’t currently support this use. Nothing has been published.`}</p>{!verdict.allowed && <><p>{verdict.negotiation_hint || 'Ask your rights team to review the missing permission before publishing.'}</p><Button variant="secondary" size="sm" onClick={() => { setCheckingOpen(false); onNavigateTab('countersign') }}>Review approvals <ArrowRight size={14} /></Button></>}<details><summary>View supporting details</summary><p>{verdict.detail || 'All required recorded permissions passed this evaluation.'}</p>{verdict.failed_ingredient && <p>Asset to review: {assetName(verdict.failed_ingredient)}</p>}<code>{verdict.reason || 'ALLOWED'}</code></details></div></div>}
    </Modal>
    <Modal isOpen={!!trace} onClose={() => setTrace(null)} title="Clearance check details">{trace && <div className="page-stack"><div className="detail-summary"><Badge variant={trace.allowed ? 'success' : 'warning'}>{trace.allowed ? 'Cleared for this use' : 'Needs attention'}</Badge><h3>{assetName(trace.asset_id)}</h3><p>{trace.channel || trace.verb} · {trace.territory || 'No region recorded'} · Decision #{trace.decision_id}</p><p>{trace.detail || 'The recorded permissions cover this specific use.'}</p></div><details><summary>Action details</summary><pre>{readableJson(trace.action_json)}</pre></details><details><summary>Supporting rights records</summary><pre>{readableJson(trace.claims_evaluated_json)}</pre></details></div>}</Modal>
    <Modal isOpen={video} onClose={() => setVideo(false)} title="The Last Echo · Sample film">{video && <><video controls autoPlay playsInline className="sample-video" poster="/media/ast_composite_v1.jpg" onError={() => toast.error('The video could not load. Please try again.')}><source src="/media/ast_video_shot_v1.mp4" type="video/mp4" /><track kind="captions" />Your browser does not support video playback.</video><p className="muted video-note">Sample AI-generated footage. Playback does not imply clearance for distribution.</p></>}</Modal>
  </div>
}
